### ISSUE TITLE
TODO: COMMENT THE BLOCK OR ADD REV AND BRANCH LOCALS

### ISSUE THREAD

**Issue by yukimono** [skiprope/skiprope#2]
Poses potential performance hit and security issue.

Related files
(design) [alpha/_footer.haml](https://github.com/skiprope/skiprope/blob/3349dff35dcbfbf4093a88c93b4e1a493bc93a70/alpha/_footer.haml#L5-L16)

**Comment by pixeldesu** [comment]
to get rid of potential security issues, wrap this block into

``` haml
- if Rails.env.development?
```

and you can also do it a bit simpler, like this:

``` haml
Current branch:
%code= `git rev-parse --abbrev-ref HEAD`
(commit
= succeed ')' do
  = `git rev-parse --short HEAD`.strip
```
